### ISSUE TITLE
_calculateStickyTreeChanges() loses new params

### ISSUE THREAD

**Issue by ViktorDolezel** [ui-router/sticky-states#10]
When using sticky states, reloading the same state with new params doesn't work as expected.
I tracked it to `_calculateStickyTreeChanges()`.

 ```
  // Rewrite the to path
   tc.to = tc.retained.concat(tc.reactivating).concat(tc.entering);
```
tc.retained has the old params so overwriting tc.to causes the transition to be rejected with "The transition was ignored" message.

Not sure what the best fix is.

**Comment by nkoterba** [comment]
Exact same problem here and it's identical to #13.
