### ISSUE TITLE
Sticky state resetting issue

### ISSUE THREAD

**Issue by aryannr97** [ui-router/sticky-states#127]
USE CASE:
Consider having two sticky states with no parent (orphan).
a) Activate first state A (works fine and remains sticky)
b) Activate second state B
Action b) resets the state A resetting it's context, after which switching states works fine
@christopherthielen please let me know if I'm wrong
Any advice would be a great help, Thanks

**Comment by rojansudev** [comment]
Encountered same problem.Existing sticky state resets on initiating a new sticky state(both orphan).Same header controller is used in the both states. Is that creating issues ?
@christopherthielen, please guide me over this
