### ISSUE TITLE
Sticky States v1.5.0 throws error in IE 11 (Object doesn't support property or method 'find')

### ISSUE THREAD

**Issue by molehillrocker** [ui-router/sticky-states#36]
The most recent version of the Sticky States plugin is currently not usable in IE 11, since it throws an error when transitioning to the initial state (see screenshot).

![image](https://user-images.githubusercontent.com/7221361/35850739-1edca7a6-0b26-11e8-8c92-a7a99e7edebb.png)

I think that this was introduced in commit [3696bf9f](https://github.com/ui-router/sticky-states/commit/3696bf9f205a63e9fef1f6103284f95d4d54708f) ([line 88](https://github.com/ui-router/sticky-states/blame/master/src/stickyStates.ts#L88)) and the reason for the error is that IE simply does not support method [Array.prototype.find()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find).

**Comment by rukhsarneyaz** [comment]
Hey @molehillrocker I am facing the same issue. I included the below polyfill in my code and now its working fine in IE 11. 

if (!Array.prototype.find) {
  Object.defineProperty(Array.prototype, 'find', {

    value: function(predicate) {

     // 1. Let O be ? ToObject(this value).

      if (this == null) {
        throw new TypeError('"this" is null or not defined');
      }

      var o = Object(this);

      // 2. Let len be ? ToLength(? Get(O, "length")).
      var len = o.length >>> 0;

      // 3. If IsCallable(predicate) is false, throw a TypeError exception.
      if (typeof predicate !== 'function') {
        throw new TypeError('predicate must be a function');
      }

      // 4. If thisArg was supplied, let T be thisArg; else let T be undefined.
      var thisArg = arguments[1];

      // 5. Let k be 0.
      var k = 0;

      // 6. Repeat, while k < len
      while (k < len) {
        // a. Let Pk be ! ToString(k).
        // b. Let kValue be ? Get(O, Pk).
        // c. Let testResult be ToBoolean(? Call(predicate, T, « kValue, k, O »)).
        // d. If testResult is true, return kValue.
        var kValue = o[k];
        if (predicate.call(thisArg, kValue, k, o)) {
          return kValue;
        }
        // e. Increase k by 1.
        k++;
      }

      // 7. Return undefined.
      return undefined;
    },
    configurable: true,
    writable: true});}

I got the code from [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill](url)

**Comment by molehillrocker** [comment]
Thanks for the hint, @rukhsarneyaz. We're also using Polyfills now, since we have a couple of other dependencies in that recently started to use language features not supported by IE11.
