### ISSUE TITLE
1.3.0 npm package doesn't include lib and lib-esm folders

### ISSUE THREAD

**Issue by ViktorDolezel** [ui-router/sticky-states#6]
I'm assuming that's why I'm getting 
**Module not found: Error: Can't resolve '@uirouter/sticky-states'**
when trying to import it.

**Comment by MatheuzSouza** [comment]
+1

**Comment by calebdwilliams** [comment]
Could this be related to some of the test cases failing so the `prepublish` script doesn't exit successfully? I tried running prepublish on my local machine and although the tests fail, the build files still show up.

**Comment by christopherthielen** [comment]
Fixed in 1.4.1

https://unpkg.com/@uirouter/sticky-states@1.4.1/
