### ISSUE TITLE
How to use pamas in sticky state

### ISSUE THREAD

**Issue by EsionMa** [ui-router/sticky-states#75]
route define params{search:"abc"},but can't remember the state?hope u can help me solve this problem

**Comment by christopherthielen** [comment]
Sticky states supports parameters.
Based on your param name, I suspect that your state is getting reloaded as the user types input into a search field.  What you are looking for is `dynamic` params.

docs: https://ui-router.github.io/ng1/docs/latest/interfaces/params.paramdeclaration.html#dynamic

Here's an example of using sticky states **and** dynamic params:
https://stackblitz.com/edit/ui-router-angularjs-sticky-states-jbkodf?file=app.js
