### ISSUE TITLE
Same component in multiple views

### ISSUE THREAD

**Issue by alexandernst** [ui-router/sticky-states#9]
Is it possible to render the same component (but a different instance, with different `data` and so on...) in a different view?

The use case is: I have a `home` state which is a sticky state. I have a modal view which is used to show a modal dialog that has a header, a footer and a main views. The header and the footer of the `home` and the modal are very very very similar (in fact the only thing that changes is the data that is rendered in the header).

If I try to render my `header` component in the `modalheader` ui-view, the `header` ui-view is cleared out.

So my question is: is there a way I can render the same component (but different instance) in two different views at the same time?

**Comment by aryannr97** [comment]
Facing same issue.If I have same controller for header which loads in two sticky states,the first initial state reloads.
